import axios from 'axios';

const localhost = 'http://localhost:5000/';

export const getProductLists = async (id) => {
    return (
        {
            "size": 38,
            "product": [
              {
                "_id": "60b5e14de7530f770bb4d659",
                "id": 0,
                "id_category": 34,
                "sku": "",
                "name": "Sách Tài Chính Cá Nhân Cho Người Việt Nam - Tặng Khóa học Online về Tài chính",
                "url_key": "sach-tai-chinh-ca-nhan-cho-nguoi-viet-nam-tang-khoa-hoc-online-ve-tai-chinh",
                "short_description": "Cuốn sách “Tài chính cá nhân dành cho người Việt Nam” và bộ bài giảng trực tuyến tặng kèm, gồm tất cả những nội dung về tài chính cá nhân, như sau:\n\nKiếm tiền: Khi còn có thể làm việc, chúng ta cần...",
                "price": 200000,
                "discount": 0,
                "discount_rate": 0,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00000_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "CÔNG TY CỔ PHẦN ĐÀO TẠO QUẢN TRỊ KINH DOANH BIZUNI",
                "author_name": "Lâm Minh Chánh",
                "index_name": "sach tai chinh ca nhan cho nguoi viet nam tang khoa hoc online ve tai chinh",
                "index_author_name": "lam minh chanh"
              },
              {
                "_id": "60b5e14de7530f770bb4d65a",
                "id": 1,
                "id_category": 35,
                "sku": "",
                "name": "Thay Đổi Cuộc Sống Với Nhân Số Học",
                "url_key": "thay-doi-cuoc-song-voi-nhan-so-hoc",
                "short_description": "Thay Đổi Cuộc Sống Với Nhân Số Học\nCuốn sách Thay đổi cuộc sống với Nhân số học là tác phẩm được chị Lê Đỗ Quỳnh Hương phát triển từ tác phẩm gốc “The Complete Book of Numerology” của tiến sỹ David A...",
                "price": 156000,
                "discount": 92000,
                "discount_rate": 37,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00001_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "First News - Trí Việt",
                "author_name": "David A. Phillips",
                "index_name": "thay doi cuoc song voi nhan so hoc",
                "index_author_name": "david a. phillips"
              },
              {
                "_id": "60b5e14de7530f770bb4d65b",
                "id": 2,
                "id_category": 30,
                "sku": "",
                "name": "Từ Điển Tiếng “Em”",
                "url_key": "tu-dien-tieng-em",
                "short_description": "TỪ ĐIỂN TIẾNG “EM” – Định nghĩa về thế giới mới!Bạn sẽ bất ngờ, khi cầm cuốn “từ điển” xinh xinh này trên tay.\nVà sẽ còn ngạc nhiên hơn nữa, khi bắt đầu đọc từng trang sách…\nDĩ nhiên là vì “Từ điển...",
                "price": 40900,
                "discount": 28100,
                "discount_rate": 41,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00002_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Skybooks",
                "author_name": "Khotudien",
                "index_name": "tu dien tieng em",
                "index_author_name": "khotudien"
              },
              {
                "_id": "60b5e14de7530f770bb4d65c",
                "id": 3,
                "id_category": 37,
                "sku": "",
                "name": "Cây Cam Ngọt Của Tôi",
                "url_key": "cay-cam-ngot-cua-toi",
                "short_description": "“Vị chua chát của cái nghèo hòa trộn với vị ngọt ngào khi khám phá ra những điều khiến cuộc đời này đáng số một tác phẩm kinh điển của Brazil.”\n- Booklist\n“Một cách nhìn cuộc sống gần như hoàn chỉnh...",
                "price": 75900,
                "discount": 32100,
                "discount_rate": 30,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00003_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Nhã Nam",
                "author_name": "",
                "index_name": "cay cam ngot cua toi",
                "index_author_name": ""
              },
              {
                "_id": "60b5e14de7530f770bb4d65d",
                "id": 4,
                "id_category": 40,
                "sku": "",
                "name": "Tô Bình Yên Vẽ Hạnh Phúc",
                "url_key": "to-binh-yen-ve-hanh-phuc",
                "short_description": "TÔ BÌNH YÊN VẼ HẠNH PHÚC – KULZSCSau thành công của cuốn sách đầu tay “Phải lòng với cô đơn” chàng họa sĩ nổi tiếng và tài năng Kulzsc đã trở lại với một cuốn sách vô cùng đặc biệt mang tên:\"Tô bình...",
                "price": 55900,
                "discount": 22100,
                "discount_rate": 28,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00004_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Skybooks",
                "author_name": "Kulzsc",
                "index_name": "to binh yen ve hanh phuc",
                "index_author_name": "kulzsc"
              },
              {
                "_id": "60b5e14de7530f770bb4d65e",
                "id": 5,
                "id_category": 26,
                "sku": "",
                "name": "Sapiens: Lược Sử Loài Người (Tái Bản Có Chỉnh Sửa) ",
                "url_key": "sapiens-luoc-su-loai-nguoi-tai-ban-co-chinh-sua",
                "short_description": "Sapiens: Lược Sử Loài Người\nSapiens, đưa chúng ta vào một chuyến đi kinh ngạc qua toàn bộ lịch sử loài người, từ những gốc rễ tiến hóa của nó đến thời đại của chủ nghĩa tư bản và kỹ thuật di truyền,...",
                "price": 124900,
                "discount": 84100,
                "discount_rate": 40,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00005_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Omega Plus",
                "author_name": "Yuval Noah Harari",
                "index_name": "sapiens luoc su loai nguoi tai ban co chinh sua",
                "index_author_name": "yuval noah harari"
              },
              {
                "_id": "60b5e14de7530f770bb4d65f",
                "id": 6,
                "id_category": 38,
                "sku": "",
                "name": "Thám Tử Lừng Danh Conan - Tập 98",
                "url_key": "tham-tu-lung-danh-conan-tap-98",
                "short_description": "Sera Masumi tiếp tục thăm dò Haibara Ai và ở thế đối đầu với Okiya Subaru!\nTrong khi đó, Conan đã tiến đến gần chân tướng của “em gái ngoài lãnh địa” - Mary…!?\nHaneda Shukichi bất ngờ gặp án mạng tại...",
                "price": 15700,
                "discount": 4300,
                "discount_rate": 22,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00006_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "NXB Kim Đồng",
                "author_name": "Gosho Aoyama",
                "index_name": "tham tu lung danh conan tap 98",
                "index_author_name": "gosho aoyama"
              },
              {
                "_id": "60b5e14de7530f770bb4d660",
                "id": 7,
                "id_category": 36,
                "sku": "",
                "name": "Combo Phát Triển Toàn Diện - Bộ sách 5 Cuốn Kỹ Năng Sống Dành Cho Trẻ",
                "url_key": "combo-bo-sach-5-cuon-ky-nang-song-danh-cho-tre",
                "short_description": "Bộ Sách Kĩ Năng Sống Dành Cho Trẻ - Mình Không Để Mẹ Lo Lắng\nBộ Sách Kĩ Năng Sống Dành Cho Trẻ - Mình Có Rất Nhiều Bạn Tốt\nBộ Sách Kĩ Năng Sống Dành Cho Trẻ - Mình Nhất Định Sẽ Thành Công\nBộ Sách Kĩ...",
                "price": 250000,
                "discount": 90000,
                "discount_rate": 26,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00007_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Nhà Sách Trí Đức",
                "author_name": "Thiên Thai (Biên Soạn)",
                "index_name": "combo bo sach 5 cuon ky nang song danh cho tre",
                "index_author_name": "thien thai (bien soan)"
              },
              {
                "_id": "60b5e14de7530f770bb4d661",
                "id": 8,
                "id_category": 23,
                "sku": "",
                "name": "Combo 2 sách: 5099 Từ Vựng HSK1-HSK6 + Tập Viết Ma Thuật 5099 Từ Vựng HSK1-HSK6 Tam Ngữ Anh Trung Việt",
                "url_key": "combo-2-sach-5099-tu-vung-hsk1-hsk6-tap-viet-ma-thuat-5099-tu-vung-hsk1-hsk6-tam-ngu-anh-trung-viet",
                "short_description": "Combo 2 sách: 5099 Từ Vựng HSK1-HSK6 + Tập Viết Ma Thuật 5099 Từ Vựng HSK1-HSK6 Tam Ngữ Anh Trung Việt\n1. Sách 5099 Từ Vựng HSK1-HSK6 Tam Ngữ Anh Trung Việt\nVới nhu cầu học tiếng Trung cũng như thi...",
                "price": 169000,
                "discount": 181000,
                "discount_rate": 52,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00008_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Nhà Xuất Bản Thanh Niên",
                "author_name": "Nguyễn Việt Dũng",
                "index_name": "combo 2 sach 5099 tu vung hsk1 hsk6 tap viet ma thuat 5099 tu vung hsk1 hsk6 tam ngu anh trung viet",
                "index_author_name": "nguyen viet dung"
              },
              {
                "_id": "60b5e14de7530f770bb4d662",
                "id": 9,
                "id_category": 25,
                "sku": "",
                "name": "Chiêm Tinh Học - Vận Dụng Trí Tuệ Về Các Vì Sao Vào Đời Sống",
                "url_key": "chiem-tinh-hoc-van-dung-tri-tue-ve-cac-vi-sao-vao-doi-song",
                "short_description": "Chiêm tinh học - Vận dụng trí tuệ về các vì sao vào đời sốngChiêm tinh học - Vận dụng trí tuệ về các vì sao vào đời sống là cuốn sách giới thiệu tới bạn đọc chiêm tinh là gì thông qua các định nghĩa,...",
                "price": 175000,
                "discount": 175000,
                "discount_rate": 50,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00009_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Công Ty Cổ Phần Văn Hóa Đông A",
                "author_name": "Carole Taylor",
                "index_name": "chiem tinh hoc van dung tri tue ve cac vi sao vao doi song",
                "index_author_name": "carole taylor"
              },
              {
                "_id": "60b5e14de7530f770bb4d663",
                "id": 10,
                "id_category": 31,
                "sku": "",
                "name": "Muôn Kiếp Nhân Sinh (Khổ Nhỏ)",
                "url_key": "muon-kiep-nhan-sinh-kho-nho",
                "short_description": "\n“Muôn kiếp nhân sinh” mang lại cho bạn đọc kho kiến thức đồ sộ và mới mẻ, những câu chuyện kỳ lạ, những kiến giải uyên bác và tiên đoán bất ngờ về hiện tại và tương lai của con người và thế giới....",
                "price": 56900,
                "discount": 41100,
                "discount_rate": 42,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00010_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "First News - Trí Việt",
                "author_name": "Nguyên Phong",
                "index_name": "muon kiep nhan sinh kho nho",
                "index_author_name": "nguyen phong"
              },
              {
                "_id": "60b5e14de7530f770bb4d664",
                "id": 11,
                "id_category": 19,
                "sku": "",
                "name": "Phương Pháp Giáo Dục Sớm Montessori Cho Trẻ Từ\n 0 – 3 Tuổi",
                "url_key": "phuong-phap-giao-duc-som-montessori-cho-tre-tu-0-3-tuoi",
                "short_description": "Bạn đang có con ở độ tuổi 0-3? Đã bao giờ bạn cảm thấy bế tắc khi bạn nói con không nghe và bạn không muốn nghe con nói? Nếu bạn gặp phải rắc rối như vậy thì đây chính là cuốn sách dành cho bạn...",
                "price": 58900,
                "discount": 40100,
                "discount_rate": 41,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00011_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "1980 Books",
                "author_name": "",
                "index_name": "phuong phap giao duc som montessori cho tre tu 0 3 tuoi",
                "index_author_name": ""
              },
              {
                "_id": "60b5e14de7530f770bb4d665",
                "id": 12,
                "id_category": 28,
                "sku": "",
                "name": "Mega 2021 - Siêu Luyện Đề 9 + THPT Quốc Gia 2021 - Toán Học",
                "url_key": "mega-2021-sieu-luyen-de-9-thpt-quoc-gia-2021-toan-hoc",
                "short_description": "Trải qua 6 năm – Đồng hành 6 mùa thi thành công, Mega Luyện đề đã trở thành bộ sách luyện đề THPT Quốc gia số 1, giúp hơn 200 nghìn bạn sĩ tử lớp 12 đỗ vào những ngôi trường Đại học mơ ước. \n \nVà năm...",
                "price": 112900,
                "discount": 72100,
                "discount_rate": 39,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00012_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Megabook",
                "author_name": "Nguyễn Xuân Nam",
                "index_name": "mega 2021 sieu luyen de 9 thpt quoc gia 2021 toan hoc",
                "index_author_name": "nguyen xuan nam"
              },
              {
                "_id": "60b5e14de7530f770bb4d666",
                "id": 13,
                "id_category": 32,
                "sku": "",
                "name": "Sài Gòn Một Thuở - Dân Ông Tạ Đó!",
                "url_key": "sai-gon-mot-thuo-dan-ong-ta-do",
                "short_description": "Là một cây bút giàu kinh nghiệm. một người con lớn lên ở khu Ông Tạ Sài Gòn vào đúng giai đoạn lịch sử nhiều biến động, tác giả Cù Mai Công đã dành nhiều tâm huyết cho tác phẩm \"Sài Gòn một thuở '...",
                "price": 50000,
                "discount": 15000,
                "discount_rate": 23,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00013_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "NXB Trẻ",
                "author_name": "Cù Mai Công",
                "index_name": "sai gon mot thuo dan ong ta do",
                "index_author_name": "cu mai cong"
              },
              {
                "_id": "60b5e14de7530f770bb4d667",
                "id": 14,
                "id_category": 33,
                "sku": "",
                "name": "Nhân tố Enzyme - Phương Thức Sống Lành Mạnh (Tái Bản 2019)",
                "url_key": "nhan-to-enzyme-phuong-thuc-song-lanh-manh-tai-ban-2019",
                "short_description": "Từ kết quả lâm sàng khi tiến hành kiểm tra dạ dày của hơn 300.000 người, bác sĩ Hiromi Shinya đã rút ra kết luận: “Người có sức khỏe tốt là người có dạ dày đẹp, ngược lại, người có sức khỏe kém là...",
                "price": 58900,
                "discount": 30100,
                "discount_rate": 34,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00014_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Thái Hà",
                "author_name": "Hiromi Shinya",
                "index_name": "nhan to enzyme phuong thuc song lanh manh tai ban 2019",
                "index_author_name": "hiromi shinya"
              },
              {
                "_id": "60b5e14de7530f770bb4d668",
                "id": 15,
                "id_category": 21,
                "sku": "",
                "name": "Python cơ bản",
                "url_key": "python-co-ban",
                "short_description": "SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trình bậc cao Python đang nổi lên như một ngôn ngữ lập trình được sử dụng NHIỀU NHẤT trên thế giới. Điều này được giải thích bằng các lý do sau:\n\nPython là...",
                "price": 125000,
                "discount": 0,
                "discount_rate": 0,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00015_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "NXB Đại Học Quốc Gia Hà Nội",
                "author_name": " Bùi Việt Hà",
                "index_name": "python co ban",
                "index_author_name": " bui viet ha"
              },
              {
                "_id": "60b5e14de7530f770bb4d669",
                "id": 16,
                "id_category": 20,
                "sku": "",
                "name": "Những Anh Hùng Của Lịch Sử",
                "url_key": "nhung-anh-hung-cua-lich-su",
                "short_description": "Những anh hùng của lịch sử là một tác phẩm cho thấy rất rõ quan điểm của Durant về việc sử gia phải đồng thời là một triết gia. Ông nỗ lực nghiên cứu, nghiền ngẫm để truy tìm những viễn tượng triết...",
                "price": 169200,
                "discount": 95800,
                "discount_rate": 36,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00016_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Nhã Nam",
                "author_name": "",
                "index_name": "nhung anh hung cua lich su",
                "index_author_name": ""
              },
              {
                "_id": "60b5e14de7530f770bb4d66a",
                "id": 17,
                "id_category": 24,
                "sku": "",
                "name": "Các Thế Giới Song Song (Tái Bản 2018)",
                "url_key": "cac-the-gioi-song-song-tai-ban-2018",
                "short_description": "Các Thế Giới Song Song\r\nMột chuyến du hành đầy trí tuệ qua các vũ trụ, được dẫn dắt tài tình bởi \"thuyền trưởng\" Michio Kaku và độc giả có dịp chiêm ngưỡng vẻ đẹp kỳ vĩ của vũ trụ kể từ vụ nổ lớn,...",
                "price": 83200,
                "discount": 44800,
                "discount_rate": 35,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00017_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Nhã Nam",
                "author_name": "Michio Kaku",
                "index_name": "cac the gioi song song tai ban 2018",
                "index_author_name": "michio kaku"
              },
              {
                "_id": "60b5e14de7530f770bb4d66b",
                "id": 18,
                "id_category": 29,
                "sku": "",
                "name": "Thánh Kinh Dưỡng Da",
                "url_key": "thanh-kinh-duong-da",
                "short_description": "“Thánh Kinh dưỡng da” - cuộc Cách mạng thần thánh đến từ “lão bà” nổi tiếng khắp toàn châu Á – Chizu Saeki.\nBản thân hình ảnh một người phụ nữ ở độ tuổi ngoài 70 và bí quyết chăm sóc da của bà trong...",
                "price": 52500,
                "discount": 52500,
                "discount_rate": 50,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00018_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Skybooks",
                "author_name": "Chizu Saeki",
                "index_name": "thanh kinh duong da",
                "index_author_name": "chizu saeki"
              },
              {
                "_id": "60b5e14de7530f770bb4d66c",
                "id": 19,
                "id_category": 27,
                "sku": "",
                "name": "Cuộc Cách Mạng Một - Cọng - Rơm",
                "url_key": "cuoc-cach-mang-mot-cong-rom",
                "short_description": "Cuộc Cách Mạng Một - Cọng - Rơm\n“Cuộc Cách Mạng Một - Cọng - Rơm” là cuốn sách nổi tiếng của Mansanobu Fukuoka, người khai sinh nông nghiệp tự nhiên của Nhật Bản và thế giới. Cuốn sách (đã được dịch...",
                "price": 90000,
                "discount": 0,
                "discount_rate": 0,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00019_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Công ty TNHH Văn Hóa & Truyền Thông Du Bút",
                "author_name": "Masanobu Fukuoka",
                "index_name": "cuoc cach mang mot cong rom",
                "index_author_name": "masanobu fukuoka"
              },
              {
                "_id": "60b5e14de7530f770bb4d66d",
                "id": 20,
                "id_category": 22,
                "sku": "",
                "name": "Kinh Tế Học Vĩ Mô",
                "url_key": "kinh-te-hoc-vi-mo",
                "short_description": "N.Gregory Mankiw là giáo sư kinh tế Đại học Harvard. Ông có nhiều bài viết và thường xuyên tham gia các chương trình tranh luận về học thuật cũng như các chính sách về kinh tế. Là một trong 25 Nhà...",
                "price": 190000,
                "discount": 69000,
                "discount_rate": 27,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00020_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Cengage",
                "author_name": "NGregory Mankiw",
                "index_name": "kinh te hoc vi mo",
                "index_author_name": "ngregory mankiw"
              },
              {
                "_id": "60b5e14de7530f770bb4d66e",
                "id": 21,
                "id_category": 39,
                "sku": "",
                "name": "Từ Điển Oxford Anh Việt 350.000 Từ (Hộp Cứng Xanh)",
                "url_key": "tu-dien-oxford-anh-viet-350-000-tu-hop-cung-xanh",
                "short_description": "Từ điển Oxford Anh Việt\nTừ điển Oxford Anh – Việt do công ty cổ phần sách MCBooks liên kết xuất bản và phát hành tại Việt Nam hiện đang được bán rất chạy trên thị trường cả nước, được đánh giá là...",
                "price": 214500,
                "discount": 83500,
                "discount_rate": 28,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00021_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "MCBOOKS",
                "author_name": "The Windy",
                "index_name": "tu dien oxford anh viet 350 000 tu hop cung xanh",
                "index_author_name": "the windy"
              },
              {
                "_id": "60b5e14de7530f770bb4d66f",
                "id": 22,
                "id_category": 9,
                "sku": "",
                "name": "English Grammar in Use Book w Ans",
                "url_key": "english-grammar-in-use-book-w-ans",
                "short_description": "The world's best-selling grammar series for learners of English. English Grammar in Use Fourth edition is an updated version of the world's best-selling grammar title. It has a fresh, appealing new...",
                "price": 137000,
                "discount": 41000,
                "discount_rate": 23,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00022_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Cambridge University",
                "author_name": "Raymond Murphy",
                "index_name": "english grammar in use book w ans",
                "index_author_name": "raymond murphy"
              },
              {
                "_id": "60b5e14de7530f770bb4d670",
                "id": 23,
                "id_category": 12,
                "sku": "",
                "name": "The Subtle Art of Not Giving a F*Ck : A Counterintuitive Approach to Living a Good Life",
                "url_key": "the-subtle-art-of-not-giving-a-f-ck-a-counterintuitive-approach-to-living-a-good-life",
                "short_description": "About the Book\n#1 International Bestseller and #1 New York Times Bestseller\nOver 2 million copies sold\nIn this generation-defining self-help guide, a superstar blogger cuts through the crap to show...",
                "price": 296000,
                "discount": 118000,
                "discount_rate": 29,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00023_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "HarperCollins",
                "author_name": "Mark Manson",
                "index_name": "the subtle art of not giving a f ck a counterintuitive approach to living a good life",
                "index_author_name": "mark manson"
              },
              {
                "_id": "60b5e14de7530f770bb4d671",
                "id": 24,
                "id_category": 10,
                "sku": "",
                "name": "Harry Potter Box Set : Books # 1 to 7 - The Complete Collection Children - Bloomsbury UK Edition (Paperback) (English Book)",
                "url_key": "harry-potter-box-set-books-1-to-7-the-complete-collection-children-bloomsbury-uk-edition-paperback-english-book",
                "short_description": "Harry Potter 7 Volume Children'S Paperback Boxed Set (Paperback - Bloomsbury UK Edition)\n\nA beautiful boxed set containing all seven Harry Potter novels in paperback. These new editions of the...",
                "price": 899000,
                "discount": 1180000,
                "discount_rate": 57,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00024_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Bloomsbury",
                "author_name": "J. K. Rowling",
                "index_name": "harry potter box set books 1 to 7 the complete collection children bloomsbury uk edition paperback english book",
                "index_author_name": "j. k. rowling"
              },
              {
                "_id": "60b5e14de7530f770bb4d672",
                "id": 25,
                "id_category": 8,
                "sku": "",
                "name": "Oxford Learner's Pocket Dictionary : A Pocket-sized Reference to English Vocabulary (Fourth Edition)",
                "url_key": "oxford-learner-s-pocket-dictionary-a-pocket-sized-reference-to-english-vocabulary-fourth-edition",
                "short_description": "\nEssential information on the basic vocabulary learners of English need to know, in a handy pocket-size.The Oxford Learner's Pocket Dictionary has over 38,000 words, phrases, and meanings giving...",
                "price": 53300,
                "discount": 21700,
                "discount_rate": 29,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00025_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Oxford University Press",
                "author_name": "",
                "index_name": "oxford learner s pocket dictionary a pocket sized reference to english vocabulary fourth edition",
                "index_author_name": ""
              },
              {
                "_id": "60b5e14de7530f770bb4d673",
                "id": 26,
                "id_category": 6,
                "sku": "",
                "name": "Diary Of A Wimpy Kid 01: A Novel In Cartoons",
                "url_key": "diary-of-a-wimpy-kid-01-a-novel-in-cartoons",
                "short_description": "The hilarious and original global bestseller Diary of a Wimpy Kid - perfect for readers of 8+ and also reluctant readers, everyone loves the adventures of Greg Heffley. Now a major film series, Diary...",
                "price": 94900,
                "discount": 136100,
                "discount_rate": 59,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00026_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Penguin Random House",
                "author_name": "Jeff Kinney",
                "index_name": "diary of a wimpy kid 01 a novel in cartoons",
                "index_author_name": "jeff kinney"
              },
              {
                "_id": "60b5e14de7530f770bb4d674",
                "id": 27,
                "id_category": 5,
                "sku": "",
                "name": "Blink: The Power of Thinking  Without Thinking",
                "url_key": "blink-the-power-of-thinking-without-thinking",
                "short_description": "\nThe landmark book that has revolutionized the way we understand leadership and decision making — from #1 bestselling author Malcolm Gladwell.In his breakthrough bestseller The Tipping Point, Malcolm...",
                "price": 95000,
                "discount": 117000,
                "discount_rate": 55,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00027_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Hachette Book Group",
                "author_name": "Malcolm Gladwell",
                "index_name": "blink the power of thinking without thinking",
                "index_author_name": "malcolm gladwell"
              },
              {
                "_id": "60b5e14de7530f770bb4d675",
                "id": 28,
                "id_category": 4,
                "sku": "",
                "name": "Totto-Chan: The Little Girl At The Window",
                "url_key": "totto-chan-the-little-girl-at-the-window",
                "short_description": "\n    \n        Totto-Chan: The Little Girl At The Window\n    \n\n\n    This engaging series of childhood recollections tells about an ideal school in Tokyo during World War II that combined learning\n   ...",
                "price": 130000,
                "discount": 129000,
                "discount_rate": 50,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00028_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Penguin Random House",
                "author_name": "Tetsuko Kuroyanagi",
                "index_name": "totto chan the little girl at the window",
                "index_author_name": "tetsuko kuroyanagi"
              },
              {
                "_id": "60b5e14de7530f770bb4d676",
                "id": 29,
                "id_category": 11,
                "sku": "",
                "name": "Sapiens : A Brief History of Humankind (Patterns of Life)",
                "url_key": "sapiens-a-brief-history-of-humankind-patterns-of-life",
                "short_description": "Planet Earth is 4.5 billion years old. In just a fraction of that time, one species among countless others has conquered it. Us. We are the most advanced and most destructive animals ever to have...",
                "price": 253900,
                "discount": 109100,
                "discount_rate": 30,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00029_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Penguin Random House",
                "author_name": "Yuval Noah Harari",
                "index_name": "sapiens a brief history of humankind patterns of life",
                "index_author_name": "yuval noah harari"
              },
              {
                "_id": "60b5e14de7530f770bb4d677",
                "id": 30,
                "id_category": 2,
                "sku": "",
                "name": "Gravity Falls: Journal 3",
                "url_key": "gravity-falls-journal-3",
                "short_description": "Gravity Falls: Journal 3 Journal 3 brims with every page ever seen on the show plus all-new pages with monsters and secrets, notes from Dipper and Mabel, and the Author's full story.\nFans of Gravity...",
                "price": 519000,
                "discount": 150600,
                "discount_rate": 22,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00030_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "",
                "author_name": "",
                "index_name": "gravity falls journal 3",
                "index_author_name": ""
              },
              {
                "_id": "60b5e14de7530f770bb4d678",
                "id": 31,
                "id_category": 3,
                "sku": "",
                "name": "The Art Book",
                "url_key": "the-art-book",
                "short_description": "Embark on a grand tour of art history with this guide to the story of art, and the big ideas and themes behind the world's most important artistic movements, artworks, and artists.\nThe Art Book...",
                "price": 386100,
                "discount": 207900,
                "discount_rate": 35,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00031_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "DK Publishing",
                "author_name": "DK",
                "index_name": "the art book",
                "index_author_name": "dk"
              },
              {
                "_id": "60b5e14de7530f770bb4d679",
                "id": 32,
                "id_category": 15,
                "sku": "",
                "name": "Men Are From Mars, Women Are From Venus: A Practical Guide For Improving Communication And Getting What You Want In Your Relationships",
                "url_key": "men-are-from-mars-women-are-from-venus-a-practical-guide-for-improving-communication-and-getting-what-you-want-in-your-relationships",
                "short_description": "Men Are From Mars, Women Are From Venus: A Practical Guide For Improving Communication And Getting What You Want In Your Relationships\r\nThe definitive self-help book from which all others derived....",
                "price": 251900,
                "discount": 78100,
                "discount_rate": 24,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00032_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "HarperCollins",
                "author_name": "John Gray",
                "index_name": "men are from mars women are from venus a practical guide for improving communication and getting what you want in your relationships",
                "index_author_name": "john gray"
              },
              {
                "_id": "60b5e14de7530f770bb4d67a",
                "id": 33,
                "id_category": 16,
                "sku": "",
                "name": "A Brief History Of Time : From Big Bang To Black Holes",
                "url_key": "a-brief-history-of-time-from-big-bang-to-black-holes",
                "short_description": "A Brief History Of Time : From Big Bang To Black Holes\r\nWas there a beginning of time? Could time run backwards?\r\nIs the universe infinite or does it have boundaries?\r\nThese are just some of the...",
                "price": 203000,
                "discount": 127000,
                "discount_rate": 38,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00033_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Penguin Random House",
                "author_name": "Stephen Hawking",
                "index_name": "a brief history of time from big bang to black holes",
                "index_author_name": "stephen hawking"
              },
              {
                "_id": "60b5e14de7530f770bb4d67b",
                "id": 34,
                "id_category": 7,
                "sku": "",
                "name": "The Cook's Book of Ingredients",
                "url_key": "the-cook-s-book-of-ingredients",
                "short_description": "The Cook's Book of Ingredients\nThe world's finest ingredients - how to buy, store, cook, and eat themGood cooking is about good ingredients - and this book shows food lovers how to get the very best...",
                "price": 841500,
                "discount": 148500,
                "discount_rate": 15,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00034_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "DK Publishing",
                "author_name": "DK",
                "index_name": "the cook s book of ingredients",
                "index_author_name": "dk"
              },
              {
                "_id": "60b5e14de7530f770bb4d67c",
                "id": 35,
                "id_category": 17,
                "sku": "",
                "name": "The Summer I Turned Pretty Complete Series (books 1-3)",
                "url_key": "the-summer-i-turned-pretty-complete-series-books-1-3",
                "short_description": "The bestselling The Summer I Turned Pretty series is now available is one gorgeous new edition, with exclusive material inside! She has only ever loved two  spends every summer at the beach. But this...",
                "price": 364650,
                "discount": 64350,
                "discount_rate": 15,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00035_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Penguin Random House",
                "author_name": "Jenny Han",
                "index_name": "the summer i turned pretty complete series books 1 3",
                "index_author_name": "jenny han"
              },
              {
                "_id": "60b5e14de7530f770bb4d67d",
                "id": 36,
                "id_category": 14,
                "sku": "",
                "name": "The Courage To Be Disliked : How to free yourself, change your life and achieve real happiness",
                "url_key": "the-courage-to-be-disliked-how-to-free-yourself-change-your-life-and-achieve-real-happiness",
                "short_description": "The Japanese phenomenon that teaches us the simple yet profound lessons required to liberate our real selves and find lasting happiness.\n\nThe Courage to be Disliked shows you how to unlock the power...",
                "price": 222750,
                "discount": 74250,
                "discount_rate": 25,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00036_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Atlantic Books",
                "author_name": "Ichiro Kishimi",
                "index_name": "the courage to be disliked how to free yourself change your life and achieve real happiness",
                "index_author_name": "ichiro kishimi"
              },
              {
                "_id": "60b5e14de7530f770bb4d67e",
                "id": 37,
                "id_category": 13,
                "sku": "",
                "name": "The Economist: The World In 2020",
                "url_key": "the-economist-the-world-in-2020",
                "short_description": "Đây là ẩn phẩm đặc biệt mà mọi người mong chờ. Mỗi năm chỉ xuất bản một số, tập hợp các sự kiện nổi bật trong năm cũng như các dự báo biến động trong năm tiếp theo. Chủ đề chính trong The World in...",
                "price": 200000,
                "discount": 197000,
                "discount_rate": 50,
                "rating_average": 0,
                "review_count": 0,
                "thumbnail_url": "http://localhost:5000/upload/images/00037_thumbnail_url.png",
                "has_ebook": false,
                "inventory_status": "available",
                "publisher": "Global Book Corporation",
                "author_name": "",
                "index_name": "the economist the world in 2020",
                "index_author_name": ""
              }
            ]
          }
    )
}

